version: 0.0.1
os: linux
files:
  - source: /
  destination: /home/ubuntu/svca
hooks:
  BeforeInstall:
    - location: aws_scripts/install_dependency
      timeout: 600
      runas: root
    - location: aws_scripts/start_server
      timeout: 600
      runas: root
  ApplicationStop:
    - location: aws_scripts/stop_server
      timeout: 600
      runas: root