version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/svca
file_exists_behavior: OVERWRITE
hooks:
  BeforeInstall:
    - location: aws_scripts/install_dependency
      timeout: 600
      runas: root
    - location: aws_scripts/start_server
      timeout: 600
      runas: root
  AfterInstall:
    - location: aws_scripts/install_pip
      timeout: 600
      runas: root
  ApplicationStop:
    - location: aws_scripts/stop_server
      timeout: 600
      runas: root
  ApplicationStart:
    - location: aws_scripts/start_server
      timeout: 600
      runas: root