# Generated by Django 3.2.4 on 2021-07-27 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210723_1717'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imageupload',
            old_name='images',
            new_name='image',
        ),
    ]
