# Generated by Django 3.2.4 on 2021-07-21 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='url',
            field=models.CharField(default='none', max_length=255),
            preserve_default=False,
        ),
    ]
