# Generated by Django 3.2.4 on 2021-07-28 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_imageupload_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='imageupload',
            name='image',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
