# Generated by Django 3.2.4 on 2021-07-22 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcontent',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
