# Generated by Django 3.2.4 on 2021-08-04 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reactneed',
            name='state',
            field=models.IntegerField(default=0),
        ),
    ]
