# Generated by Django 3.2.4 on 2021-06-15 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reactmember',
            options={'managed': True, 'permissions': [('is_member', 'Is a member and conly view specific information')]},
        ),
        migrations.AlterModelOptions(
            name='reactneed',
            options={'managed': True},
        ),
    ]
