# Generated by Django 3.2.4 on 2021-08-18 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_reactneed_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='reactneed',
            name='housing',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
