# Generated by Django 3.2.4 on 2021-06-24 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20210623_1721'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReactVulnerableGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'react_vulnerable_group',
            },
        ),
        migrations.AddField(
            model_name='reactneed',
            name='vulnerable_group',
            field=models.ManyToManyField(to='members.ReactVulnerableGroup'),
        ),
    ]
