# Generated by Django 3.2.4 on 2021-06-15 20:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20210615_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='reactmember',
            name='account_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
