# Generated by Django 3.2.4 on 2021-06-24 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_auto_20210624_1538'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reactneed',
            old_name='vulnerable_group',
            new_name='vulnerable_groups',
        ),
        migrations.RenameField(
            model_name='reactvulnerablegroup',
            old_name='group_name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='reactneed',
            name='state',
            field=models.IntegerField(null=True),
        ),
    ]
