# Generated by Django 3.2.4 on 2021-08-24 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_reactneed_housing'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DjangoContentType',
        ),
        migrations.DeleteModel(
            name='DjangoMigrations',
        ),
        migrations.DeleteModel(
            name='DjangoSession',
        ),
        migrations.DeleteModel(
            name='Paragraph',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='PostLike',
        ),
        migrations.AlterModelOptions(
            name='reactmember',
            options={'managed': True, 'permissions': [('is_member', 'Is a member and can only view specific information')]},
        ),
        migrations.AlterField(
            model_name='reactmember',
            name='contact_type',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reactmember',
            name='location_type',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reactmember',
            name='member_type',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reactmember',
            name='phone',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='reactneed',
            name='contact_reference',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='reactneed',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='reactneed',
            name='family18',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reactneed',
            name='family19',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reactneed',
            name='family55',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reactneed',
            name='housing',
            field=models.IntegerField(default=-1),
        ),
    ]
