# Generated by Django 3.2.4 on 2021-06-15 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_reactmember_account_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reactmember',
            old_name='account_id',
            new_name='account',
        ),
    ]
