# Generated by Django 3.2.4 on 2021-06-25 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_alter_reactuser_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='reactneed',
            name='family18',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reactneed',
            name='family19',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reactneed',
            name='family55',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
