# Generated by Django 3.2.4 on 2021-08-26 20:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_alter_reactmember_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reactfollowup',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='reactfollowup',
            name='worker',
            field=models.CharField(blank=True, default='none', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reactneedassessment',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='reactneedworking',
            name='need',
            field=models.TextField(),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reactneedworking',
            name='need_met',
            field=models.TextField(),
            preserve_default=False,
        ),
    ]
