# Generated by Django 3.2.4 on 2021-06-28 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_auto_20210628_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reactneedworking',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
