# Generated by Django 3.2.4 on 2021-06-29 01:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_alter_reactneedworking_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reactfollowup',
            name='date',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='reactfollowup',
            name='response',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.reactneed'),
        ),
    ]
