# Generated by Django 3.2.4 on 2021-06-29 22:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_auto_20210628_1854'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReactNeedAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment', models.TextField()),
                ('date', models.DateField(default=datetime.date.today, null=True)),
                ('author', models.TextField(max_length=255, null=True)),
                ('response', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.reactneed')),
            ],
            options={
                'db_table': 'react_need_assessment',
            },
        ),
    ]
