# Generated by Django 3.2.4 on 2021-06-29 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0011_reactneedassessment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reactneedassessment',
            name='response',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.reactneed', unique=True),
        ),
    ]
